### ISSUE TITLE
suggestion: put a to-do list here in the issues.

### ISSUE THREAD

**Issue by Berchez** [PicartaAI/Picarta-API#1]
I think this project is really cool and I bet it has a lot of potential.

I think it would be interesting from a community point of view if you could list some bugs and possible new features here in the issues. The github community can help you to improve this repo

**Comment by PicartaAI** [comment]
@Berchez Thanks for sharing! We're open to any suggestions and bug reports from our community.

Also, I can forward you to our [Discord](https://discord.com/invite/g5BAd2UFbs) channel where we can discuss some ideas on how to improve Picarta.
